### ISSUE TITLE
Change plain links to app names

### ISSUE THREAD

**Issue by cheeaun** [cheeaun/awesome-hacker-news#1]
Basically have to go through all links, get the names and format it to `[NAME](LINK)`.

- No more `[NAME](LINK) by [PERSON]` because it's pretty hard to maintain
- Sorting them alphabetically would be great, with **defunct** links/products/apps sorted at the bottom
- Changing from `LINK` to `[NAME](LINK)` would be nice as it's more readable.

---

Notes (Markdown format):

`LINK` = `https://showcase.metamate.io/hackernews-trends`
`[NAME](LINK)` = `[HackerNews Trends](https://showcase.metamate.io/hackernews-trends)`

**Comment by willswire** [comment]
@cheeaun, just submitted PR #44 which changes plain links to app names. I also removed the deprecated projects and updated the table of contents.
