### ISSUE TITLE
Things that have been deleted/404 should be moved, removed, or demphasized

### ISSUE THREAD

**Issue by yehosef** [cheeaun/awesome-hacker-news#12]
There are many projects that are defunct and they clutter up the list.  I think they should either be removed or moved to some kind of deadpool at the bottom of the list or in another document (might be better - could retain the structure).

I'm not submitting a pull request because I don't know what others think about this problem and approach.

**Comment by cheeaun** [comment]
Hey thanks for your comment! I think moving them to a deadpool at the bottom would be good for now.

**Comment by AdrienLemaire** [comment]
Thanks for making this awesome list!

Here's another dead link:
http://hnpaper.forge.partlab.io/
502 Bad Gateway

**Comment by willswire** [comment]
@cheeaun if folks want their extensions/resources added back to the list, they can always submit a PR with an updated URL and title. What are your thoughts on keeping the deprecated links in the README?

**Comment by cheeaun** [comment]
It's been a while, now I think it's better to remove them from the list. Initially I thought it'll be good to show how the _ecosystem_ evolves over time, but they don't seem useful after some time, especially few **years**.

@willswire I will merge your PR, thanks!
