### ISSUE TITLE
Section for HN-related resources

### ISSUE THREAD

**Issue by antontarasenko** [cheeaun/awesome-hacker-news#6]
@cheeaun I wanted to add a link to [HN meetups list](https://github.com/antontarasenko/hacker-news-groups) (disclaimer: I maintain it), but haven't found the section for resources (only for apps) and suggest adding one to the list.

I can do that with a pull request, if you don't mind.

**Comment by cheeaun** [comment]
@antontarasenko wow that would be great! Thanks!

**Comment by antontarasenko** [comment]
@cheeaun Great! The pull request: https://github.com/cheeaun/awesome-hacker-news/pull/7
